name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64

      - name: deps
        run: python -m pip install -U pip wheel setuptools

      - name: wheel
        run: python setup.py bdist_wheel

  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: docker build . -f tests/Dockerfile -t tests

      - name: test
        run: docker run --rm -t tests

  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: docker build . -f tests/coverage/Dockerfile -t coverage

      - name: coverage
        run: docker run --rm -t coverage

  codestyle:
    name: codestyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: docker build . -f tests/codestyle/Dockerfile -t codestyle

      - name: codestyle
        run: docker run --rm -t codestyle

  documentation:
    name: documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: docker build . -f tests/documentation/Dockerfile -t documentation

      - name: documentation
        run: docker run --rm -t documentation
